void main() {

  try {
   print(10~/0);
  } catch (e) {
   print("Error is Occured");
  } finally{
    print("Finally is exceuted successfully");

  }
  print("Flutter Developer");

}